name: Auto Update Branches

on:
  push:
    branches-ignore:
      - '*'
  pull_request:
    types:
      - closed

jobs:
  update-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar el evento de merge en main
        id: check-merge
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
        run: |
          echo "::set-output name=merge::true"
        shell: bash

      - name: Actualizar Javier
        if: steps.check-merge.outputs.merge == 'true'
        run: |
          git checkout Javier
          git pull origin main
          git push origin Javier
        shell: bash

      - name: Actualizar RafaelWB
        if: steps.check-merge.outputs.merge == 'true'
        run: |
          git checkout RafaelWB
          git pull origin main
          git push origin RafaelWB
        shell: bash

      - name: Actualizar Ernesto
        if: steps.check-merge.outputs.merge == 'true'
        run: |
          git checkout Ernesto
          git pull origin main
          git push origin Ernesto
        shell: bash


